name: disclaimer
version: 0.1.0.0

dependencies:
  - base

executables:
  disclaimer:
    main: Main.hs
    source-dirs: app
    dependencies:
      - disclaimer
      - transformers

library:
  exposed-modules:
    - Disclaimer
    - SimpleCheck
    - SimpleWriter
  source-dirs: src
  dependencies:
    - transformers

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - disclaimer
      - hspec
      - QuickCheck
      - transformers

benchmarks:
  bench:
    main: Benchmark.hs
    source-dirs: bench
    dependencies:
      - disclaimer
      - criterion
